// This file is auto-generated by @hey-api/openapi-ts

export const ActivityLogCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            title: 'Title'
        },
        content: {
            type: 'string',
            maxLength: 2000,
            title: 'Content'
        },
        date: {
            type: 'string',
            format: 'date',
            title: 'Date'
        },
        attachment_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 512
                },
                {
                    type: 'null'
                }
            ],
            title: 'Attachment Url'
        },
        internship_id: {
            type: 'string',
            format: 'uuid',
            title: 'Internship Id'
        }
    },
    type: 'object',
    required: ['title', 'content', 'internship_id'],
    title: 'ActivityLogCreate'
} as const;

export const ActivityLogEntriesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ActivityLogEntryPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ActivityLogEntriesPublic'
} as const;

export const ActivityLogEntryCreateSchema = {
    properties: {
        date: {
            type: 'string',
            format: 'date',
            title: 'Date'
        },
        content: {
            type: 'string',
            maxLength: 2000,
            title: 'Content'
        },
        hours: {
            type: 'integer',
            maximum: 24,
            minimum: 0,
            title: 'Hours'
        },
        internship_request_id: {
            type: 'string',
            format: 'uuid',
            title: 'Internship Request Id'
        }
    },
    type: 'object',
    required: ['date', 'content', 'hours', 'internship_request_id'],
    title: 'ActivityLogEntryCreate'
} as const;

export const ActivityLogEntryPublicSchema = {
    properties: {
        date: {
            type: 'string',
            format: 'date',
            title: 'Date'
        },
        content: {
            type: 'string',
            maxLength: 2000,
            title: 'Content'
        },
        hours: {
            type: 'integer',
            maximum: 24,
            minimum: 0,
            title: 'Hours'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        internship_request_id: {
            type: 'string',
            format: 'uuid',
            title: 'Internship Request Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['date', 'content', 'hours', 'id', 'internship_request_id', 'owner_id'],
    title: 'ActivityLogEntryPublic'
} as const;

export const ActivityLogPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            title: 'Title'
        },
        content: {
            type: 'string',
            maxLength: 2000,
            title: 'Content'
        },
        date: {
            type: 'string',
            format: 'date',
            title: 'Date'
        },
        attachment_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 512
                },
                {
                    type: 'null'
                }
            ],
            title: 'Attachment Url'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        internship_id: {
            type: 'string',
            format: 'uuid',
            title: 'Internship Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        feedback: {
            items: {
                '$ref': '#/components/schemas/TutorFeedbackPublic'
            },
            type: 'array',
            title: 'Feedback',
            default: []
        },
        owner: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/UserMinimal'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['title', 'content', 'id', 'internship_id', 'owner_id', 'created_at'],
    title: 'ActivityLogPublic'
} as const;

export const ActivityLogsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ActivityLogPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ActivityLogsPublic'
} as const;

export const AlertItemSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        type: {
            type: 'string',
            title: 'Type'
        },
        severity: {
            type: 'string',
            title: 'Severity'
        },
        message: {
            type: 'string',
            title: 'Message'
        },
        dossier_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Dossier Id'
        },
        created_at: {
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'type', 'severity', 'message', 'dossier_id', 'created_at'],
    title: 'AlertItem'
} as const;

export const ApprovalLevelSchema = {
    type: 'string',
    enum: ['N1', 'N2', 'N3'],
    title: 'ApprovalLevel'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const Body_pdf_extract_pdf_dataSchema = {
    properties: {
        files: {
            items: {
                type: 'string',
                format: 'binary'
            },
            type: 'array',
            title: 'Files'
        }
    },
    type: 'object',
    required: ['files'],
    title: 'Body_pdf-extract_pdf_data'
} as const;

export const Body_uploads_upload_convention_pdfSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_uploads-upload_convention_pdf'
} as const;

export const Body_user_documents_upload_user_documentSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_user-documents-upload_user_document'
} as const;

export const ConventionCreateSchema = {
    properties: {
        document_name: {
            type: 'string',
            maxLength: 255,
            title: 'Document Name'
        },
        signature_step: {
            type: 'integer',
            maximum: 8,
            minimum: 1,
            title: 'Signature Step',
            default: 1
        },
        status: {
            type: 'string',
            maxLength: 50,
            title: 'Status',
            default: 'pending'
        },
        approval_level: {
            '$ref': '#/components/schemas/ApprovalLevel',
            default: 'N1'
        },
        admin_status: {
            type: 'string',
            maxLength: 50,
            title: 'Admin Status',
            default: 'pending'
        },
        internship_request_id: {
            type: 'string',
            format: 'uuid',
            title: 'Internship Request Id'
        }
    },
    type: 'object',
    required: ['document_name', 'internship_request_id'],
    title: 'ConventionCreate'
} as const;

export const ConventionPublicSchema = {
    properties: {
        document_name: {
            type: 'string',
            maxLength: 255,
            title: 'Document Name'
        },
        signature_step: {
            type: 'integer',
            maximum: 8,
            minimum: 1,
            title: 'Signature Step',
            default: 1
        },
        status: {
            type: 'string',
            maxLength: 50,
            title: 'Status',
            default: 'pending'
        },
        approval_level: {
            '$ref': '#/components/schemas/ApprovalLevel',
            default: 'N1'
        },
        admin_status: {
            type: 'string',
            maxLength: 50,
            title: 'Admin Status',
            default: 'pending'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        internship_request_id: {
            type: 'string',
            format: 'uuid',
            title: 'Internship Request Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        },
        owner: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/UserPublic'
                },
                {
                    type: 'null'
                }
            ]
        },
        internship_request: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/InternshipRequestPublic'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['document_name', 'id', 'internship_request_id', 'owner_id'],
    title: 'ConventionPublic'
} as const;

export const ConventionUpdateSchema = {
    properties: {
        document_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Document Name'
        },
        signature_step: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 8,
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Signature Step'
        },
        status: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Status'
        },
        approval_level: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ApprovalLevel'
                },
                {
                    type: 'null'
                }
            ]
        },
        admin_status: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Admin Status'
        }
    },
    type: 'object',
    title: 'ConventionUpdate'
} as const;

export const ConventionsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ConventionPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ConventionsPublic'
} as const;

export const DashboardOverviewResponseSchema = {
    properties: {
        internships: {
            '$ref': '#/components/schemas/InternshipSummary'
        },
        dossiers: {
            '$ref': '#/components/schemas/DossierSummary'
        },
        sla: {
            '$ref': '#/components/schemas/SLASummary'
        },
        signature: {
            '$ref': '#/components/schemas/SignatureSummary'
        },
        alerts: {
            items: {
                '$ref': '#/components/schemas/AlertItem'
            },
            type: 'array',
            title: 'Alerts'
        },
        system_health: {
            items: {
                '$ref': '#/components/schemas/SystemHealthItem'
            },
            type: 'array',
            title: 'System Health'
        },
        workflow_chart: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Workflow Chart'
        },
        visitor_chart: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Visitor Chart'
        },
        timestamp: {
            type: 'string',
            title: 'Timestamp'
        }
    },
    type: 'object',
    required: ['internships', 'dossiers', 'sla', 'signature', 'alerts', 'system_health', 'workflow_chart', 'visitor_chart', 'timestamp'],
    title: 'DashboardOverviewResponse'
} as const;

export const DocumentTypeSchema = {
    type: 'string',
    enum: ['cv', 'certificate', 'phd_doc', 'other'],
    title: 'DocumentType'
} as const;

export const DossierSummarySchema = {
    properties: {
        total_dossiers: {
            type: 'integer',
            title: 'Total Dossiers'
        },
        active_dossiers: {
            type: 'integer',
            title: 'Active Dossiers'
        },
        completed_dossiers: {
            type: 'integer',
            title: 'Completed Dossiers'
        },
        pending_dossiers: {
            type: 'integer',
            title: 'Pending Dossiers'
        },
        pending_verification: {
            type: 'integer',
            title: 'Pending Verification'
        }
    },
    type: 'object',
    required: ['total_dossiers', 'active_dossiers', 'completed_dossiers', 'pending_dossiers', 'pending_verification'],
    title: 'DossierSummary'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const InternshipOfferBaseSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 500,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 5000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        source_url: {
            type: 'string',
            maxLength: 1000,
            title: 'Source Url'
        },
        published_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Published Date'
        },
        target_audience: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Target Audience',
            default: 'both'
        },
        mobility_type: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Mobility Type',
            default: 'national'
        },
        keywords: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Keywords'
        },
        translated_description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Translated Description'
        },
        specialty: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Specialty'
        },
        required_level: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Required Level'
        },
        required_language: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Required Language'
        },
        gpa_requirement: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Gpa Requirement'
        },
        university_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'University Name'
        },
        university_logo: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'University Logo'
        },
        country_flag: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 10
                },
                {
                    type: 'null'
                }
            ],
            title: 'Country Flag'
        },
        country: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Country'
        },
        country_code: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 5
                },
                {
                    type: 'null'
                }
            ],
            title: 'Country Code'
        }
    },
    type: 'object',
    required: ['title', 'source_url'],
    title: 'InternshipOfferBase'
} as const;

export const InternshipOfferPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 500,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 5000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        source_url: {
            type: 'string',
            maxLength: 1000,
            title: 'Source Url'
        },
        published_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Published Date'
        },
        target_audience: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Target Audience',
            default: 'both'
        },
        mobility_type: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Mobility Type',
            default: 'national'
        },
        keywords: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Keywords'
        },
        translated_description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Translated Description'
        },
        specialty: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Specialty'
        },
        required_level: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Required Level'
        },
        required_language: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Required Language'
        },
        gpa_requirement: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Gpa Requirement'
        },
        university_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'University Name'
        },
        university_logo: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'University Logo'
        },
        country_flag: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 10
                },
                {
                    type: 'null'
                }
            ],
            title: 'Country Flag'
        },
        country: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Country'
        },
        country_code: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 5
                },
                {
                    type: 'null'
                }
            ],
            title: 'Country Code'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['title', 'source_url', 'id'],
    title: 'InternshipOfferPublic'
} as const;

export const InternshipOffersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/InternshipOfferPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'InternshipOffersPublic'
} as const;

export const InternshipReportCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            title: 'Title'
        },
        file_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 512
                },
                {
                    type: 'null'
                }
            ],
            title: 'File Url'
        },
        status: {
            '$ref': '#/components/schemas/ReportStatus',
            default: 'pending'
        },
        feedback: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Feedback'
        },
        internship_request_id: {
            type: 'string',
            format: 'uuid',
            title: 'Internship Request Id'
        }
    },
    type: 'object',
    required: ['title', 'internship_request_id'],
    title: 'InternshipReportCreate'
} as const;

export const InternshipReportPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            title: 'Title'
        },
        file_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 512
                },
                {
                    type: 'null'
                }
            ],
            title: 'File Url'
        },
        status: {
            '$ref': '#/components/schemas/ReportStatus',
            default: 'pending'
        },
        feedback: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Feedback'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        internship_request_id: {
            type: 'string',
            format: 'uuid',
            title: 'Internship Request Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        submitted_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Submitted At'
        },
        reviewed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reviewed At'
        }
    },
    type: 'object',
    required: ['title', 'id', 'internship_request_id', 'owner_id'],
    title: 'InternshipReportPublic'
} as const;

export const InternshipReportsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/InternshipReportPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'InternshipReportsPublic'
} as const;

export const InternshipRequestCreateSchema = {
    properties: {
        student_name: {
            type: 'string',
            maxLength: 255,
            title: 'Student Name'
        },
        registration_number: {
            type: 'string',
            maxLength: 50,
            title: 'Registration Number'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        birth_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Birth Date'
        },
        company_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Company Name'
        },
        company_address: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Company Address'
        },
        mission_title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Mission Title'
        },
        mission_description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Mission Description'
        },
        start_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Start Date'
        },
        end_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Date'
        },
        status: {
            '$ref': '#/components/schemas/InternshipStatus',
            default: 'draft'
        },
        verification_status: {
            '$ref': '#/components/schemas/VerificationStatus',
            default: 'idle'
        },
        progress: {
            type: 'integer',
            maximum: 100,
            minimum: 0,
            title: 'Progress',
            default: 0
        },
        current_step: {
            type: 'integer',
            maximum: 8,
            minimum: 1,
            title: 'Current Step',
            default: 1
        },
        supervisor_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Supervisor Name'
        }
    },
    type: 'object',
    required: ['student_name', 'registration_number'],
    title: 'InternshipRequestCreate'
} as const;

export const InternshipRequestPublicSchema = {
    properties: {
        student_name: {
            type: 'string',
            maxLength: 255,
            title: 'Student Name'
        },
        registration_number: {
            type: 'string',
            maxLength: 50,
            title: 'Registration Number'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        birth_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Birth Date'
        },
        company_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Company Name'
        },
        company_address: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Company Address'
        },
        mission_title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Mission Title'
        },
        mission_description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Mission Description'
        },
        start_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Start Date'
        },
        end_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Date'
        },
        status: {
            '$ref': '#/components/schemas/InternshipStatus',
            default: 'draft'
        },
        verification_status: {
            '$ref': '#/components/schemas/VerificationStatus',
            default: 'idle'
        },
        progress: {
            type: 'integer',
            maximum: 100,
            minimum: 0,
            title: 'Progress',
            default: 0
        },
        current_step: {
            type: 'integer',
            maximum: 8,
            minimum: 1,
            title: 'Current Step',
            default: 1
        },
        supervisor_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Supervisor Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['student_name', 'registration_number', 'id', 'owner_id'],
    title: 'InternshipRequestPublic'
} as const;

export const InternshipRequestUpdateSchema = {
    properties: {
        student_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Student Name'
        },
        registration_number: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Registration Number'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        birth_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Birth Date'
        },
        company_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Company Name'
        },
        company_address: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Company Address'
        },
        mission_title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Mission Title'
        },
        mission_description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Mission Description'
        },
        start_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Start Date'
        },
        end_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Date'
        },
        status: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/InternshipStatus'
                },
                {
                    type: 'null'
                }
            ]
        },
        verification_status: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/VerificationStatus'
                },
                {
                    type: 'null'
                }
            ]
        },
        progress: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 100,
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Progress'
        },
        current_step: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 8,
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Current Step'
        },
        supervisor_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Supervisor Name'
        }
    },
    type: 'object',
    title: 'InternshipRequestUpdate'
} as const;

export const InternshipRequestsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/InternshipRequestPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'InternshipRequestsPublic'
} as const;

export const InternshipStatusSchema = {
    type: 'string',
    enum: ['draft', 'pending_verification', 'pending_signature', 'active', 'completed', 'blocked'],
    title: 'InternshipStatus'
} as const;

export const InternshipSummarySchema = {
    properties: {
        total_internships: {
            type: 'integer',
            title: 'Total Internships'
        },
        latest_internships: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Latest Internships'
        },
        new_items_7d: {
            type: 'integer',
            title: 'New Items 7D'
        }
    },
    type: 'object',
    required: ['total_internships', 'latest_internships', 'new_items_7d'],
    title: 'InternshipSummary'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const MobilityFileCreateSchema = {
    properties: {
        reference_code: {
            type: 'string',
            maxLength: 20,
            title: 'Reference Code'
        },
        student_name: {
            type: 'string',
            maxLength: 255,
            title: 'Student Name'
        },
        destination: {
            type: 'string',
            maxLength: 500,
            title: 'Destination'
        },
        mobility_type: {
            '$ref': '#/components/schemas/MobilityType'
        },
        approval_level: {
            '$ref': '#/components/schemas/ApprovalLevel',
            default: 'N1'
        },
        priority: {
            '$ref': '#/components/schemas/Priority',
            default: 'Medium'
        },
        tags: {
            type: 'string',
            maxLength: 500,
            title: 'Tags',
            default: ''
        },
        status: {
            type: 'string',
            maxLength: 50,
            title: 'Status',
            default: 'pending'
        },
        origin_university: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Origin University'
        },
        visa_status: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Visa Status'
        },
        file_transfer_status: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'File Transfer Status',
            default: 'pending'
        }
    },
    type: 'object',
    required: ['reference_code', 'student_name', 'destination', 'mobility_type'],
    title: 'MobilityFileCreate'
} as const;

export const MobilityFilePublicSchema = {
    properties: {
        reference_code: {
            type: 'string',
            maxLength: 20,
            title: 'Reference Code'
        },
        student_name: {
            type: 'string',
            maxLength: 255,
            title: 'Student Name'
        },
        destination: {
            type: 'string',
            maxLength: 500,
            title: 'Destination'
        },
        mobility_type: {
            '$ref': '#/components/schemas/MobilityType'
        },
        approval_level: {
            '$ref': '#/components/schemas/ApprovalLevel',
            default: 'N1'
        },
        priority: {
            '$ref': '#/components/schemas/Priority',
            default: 'Medium'
        },
        tags: {
            type: 'string',
            maxLength: 500,
            title: 'Tags',
            default: ''
        },
        status: {
            type: 'string',
            maxLength: 50,
            title: 'Status',
            default: 'pending'
        },
        origin_university: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Origin University'
        },
        visa_status: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Visa Status'
        },
        file_transfer_status: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'File Transfer Status'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['reference_code', 'student_name', 'destination', 'mobility_type', 'id', 'owner_id'],
    title: 'MobilityFilePublic'
} as const;

export const MobilityFileUpdateSchema = {
    properties: {
        reference_code: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reference Code'
        },
        student_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Student Name'
        },
        destination: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Destination'
        },
        mobility_type: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/MobilityType'
                },
                {
                    type: 'null'
                }
            ]
        },
        approval_level: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ApprovalLevel'
                },
                {
                    type: 'null'
                }
            ]
        },
        priority: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/Priority'
                },
                {
                    type: 'null'
                }
            ]
        },
        tags: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tags'
        },
        status: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Status'
        },
        origin_university: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Origin University'
        },
        visa_status: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Visa Status'
        },
        file_transfer_status: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'File Transfer Status'
        }
    },
    type: 'object',
    title: 'MobilityFileUpdate'
} as const;

export const MobilityFilesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/MobilityFilePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'MobilityFilesPublic'
} as const;

export const MobilityTypeSchema = {
    type: 'string',
    enum: ['nationale', 'internationale'],
    title: 'MobilityType'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PDFExtractionPublicSchema = {
    properties: {
        filename: {
            type: 'string',
            maxLength: 255,
            title: 'Filename'
        },
        extracted_data: {
            additionalProperties: true,
            type: 'object',
            title: 'Extracted Data'
        },
        status: {
            type: 'string',
            maxLength: 50,
            title: 'Status',
            default: 'success'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        owner: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/UserPublic'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['filename', 'id', 'owner_id', 'created_at'],
    title: 'PDFExtractionPublic'
} as const;

export const PDFExtractionsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/PDFExtractionPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'PDFExtractionsPublic'
} as const;

export const PartnerTypeSchema = {
    type: 'string',
    enum: ['university', 'company'],
    title: 'PartnerType'
} as const;

export const PartnershipCreateSchema = {
    properties: {
        partner_name: {
            type: 'string',
            maxLength: 255,
            title: 'Partner Name'
        },
        partner_type: {
            '$ref': '#/components/schemas/PartnerType',
            default: 'company'
        },
        contact_email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contact Email'
        },
        contact_phone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contact Phone'
        },
        start_date: {
            type: 'string',
            format: 'date',
            title: 'Start Date'
        },
        end_date: {
            type: 'string',
            format: 'date',
            title: 'End Date'
        },
        status: {
            '$ref': '#/components/schemas/PartnershipStatus',
            default: 'active'
        },
        document_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 512
                },
                {
                    type: 'null'
                }
            ],
            title: 'Document Url'
        }
    },
    type: 'object',
    required: ['partner_name', 'start_date', 'end_date'],
    title: 'PartnershipCreate'
} as const;

export const PartnershipPublicSchema = {
    properties: {
        partner_name: {
            type: 'string',
            maxLength: 255,
            title: 'Partner Name'
        },
        partner_type: {
            '$ref': '#/components/schemas/PartnerType',
            default: 'company'
        },
        contact_email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contact Email'
        },
        contact_phone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contact Phone'
        },
        start_date: {
            type: 'string',
            format: 'date',
            title: 'Start Date'
        },
        end_date: {
            type: 'string',
            format: 'date',
            title: 'End Date'
        },
        status: {
            '$ref': '#/components/schemas/PartnershipStatus',
            default: 'active'
        },
        document_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 512
                },
                {
                    type: 'null'
                }
            ],
            title: 'Document Url'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['partner_name', 'start_date', 'end_date', 'id'],
    title: 'PartnershipPublic'
} as const;

export const PartnershipStatusSchema = {
    type: 'string',
    enum: ['active', 'expired', 'pending'],
    title: 'PartnershipStatus'
} as const;

export const PartnershipUpdateSchema = {
    properties: {
        partner_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Partner Name'
        },
        partner_type: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/PartnerType'
                },
                {
                    type: 'null'
                }
            ]
        },
        contact_email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contact Email'
        },
        contact_phone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contact Phone'
        },
        start_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Start Date'
        },
        end_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Date'
        },
        status: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/PartnershipStatus'
                },
                {
                    type: 'null'
                }
            ]
        },
        document_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 512
                },
                {
                    type: 'null'
                }
            ],
            title: 'Document Url'
        }
    },
    type: 'object',
    title: 'PartnershipUpdate'
} as const;

export const PartnershipsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/PartnershipPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'PartnershipsPublic'
} as const;

export const PrioritySchema = {
    type: 'string',
    enum: ['Low', 'Medium', 'High', 'Critical'],
    title: 'Priority'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const RecommendationResponseSchema = {
    properties: {
        results: {
            items: {
                '$ref': '#/components/schemas/RecommendationResultItem'
            },
            type: 'array',
            title: 'Results'
        },
        is_fallback: {
            type: 'boolean',
            title: 'Is Fallback'
        },
        message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Message'
        }
    },
    type: 'object',
    required: ['results', 'is_fallback', 'message'],
    title: 'RecommendationResponse'
} as const;

export const RecommendationResultItemSchema = {
    properties: {
        offer: {
            '$ref': '#/components/schemas/InternshipOfferPublic'
        },
        score: {
            type: 'number',
            title: 'Score'
        },
        breakdown: {
            anyOf: [
                {
                    additionalProperties: {
                        type: 'number'
                    },
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Breakdown'
        },
        warnings: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Warnings'
        }
    },
    type: 'object',
    required: ['offer', 'score'],
    title: 'RecommendationResultItem'
} as const;

export const ReportStatusSchema = {
    type: 'string',
    enum: ['pending', 'reviewed', 'approved', 'rejected'],
    title: 'ReportStatus'
} as const;

export const SLASummarySchema = {
    properties: {
        total_dossiers: {
            type: 'integer',
            title: 'Total Dossiers'
        },
        on_time_count: {
            type: 'integer',
            title: 'On Time Count'
        },
        breached_count: {
            type: 'integer',
            title: 'Breached Count'
        },
        breach_rate: {
            type: 'number',
            title: 'Breach Rate'
        }
    },
    type: 'object',
    required: ['total_dossiers', 'on_time_count', 'breached_count', 'breach_rate'],
    title: 'SLASummary'
} as const;

export const SignatureSummarySchema = {
    properties: {
        average_progress: {
            type: 'number',
            title: 'Average Progress'
        },
        stalled_dossiers: {
            type: 'integer',
            title: 'Stalled Dossiers'
        },
        completed_signatures: {
            type: 'integer',
            title: 'Completed Signatures'
        }
    },
    type: 'object',
    required: ['average_progress', 'stalled_dossiers', 'completed_signatures'],
    title: 'SignatureSummary'
} as const;

export const StageRequestCreateSchema = {
    properties: {
        selected_mobility_type: {
            type: 'string',
            maxLength: 50,
            title: 'Selected Mobility Type'
        },
        selected_interests: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Selected Interests'
        },
        duration_preference: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Duration Preference'
        },
        specialty: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Specialty'
        },
        level: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Level'
        },
        language: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Language'
        },
        gpa: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Gpa'
        }
    },
    type: 'object',
    required: ['selected_mobility_type'],
    title: 'StageRequestCreate'
} as const;

export const SystemHealthItemSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        latency: {
            type: 'string',
            title: 'Latency'
        }
    },
    type: 'object',
    required: ['name', 'status', 'latency'],
    title: 'SystemHealthItem'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const TutorEvaluationCreateSchema = {
    properties: {
        rating: {
            type: 'integer',
            maximum: 5,
            minimum: 1,
            title: 'Rating'
        },
        comment: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Comment'
        },
        internship_request_id: {
            type: 'string',
            format: 'uuid',
            title: 'Internship Request Id'
        }
    },
    type: 'object',
    required: ['rating', 'internship_request_id'],
    title: 'TutorEvaluationCreate'
} as const;

export const TutorEvaluationPublicSchema = {
    properties: {
        rating: {
            type: 'integer',
            maximum: 5,
            minimum: 1,
            title: 'Rating'
        },
        comment: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Comment'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        internship_request_id: {
            type: 'string',
            format: 'uuid',
            title: 'Internship Request Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['rating', 'id', 'internship_request_id', 'owner_id'],
    title: 'TutorEvaluationPublic'
} as const;

export const TutorFeedbackCreateSchema = {
    properties: {
        comment: {
            type: 'string',
            maxLength: 2000,
            title: 'Comment'
        },
        rating: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 5,
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rating'
        },
        log_id: {
            type: 'string',
            format: 'uuid',
            title: 'Log Id'
        }
    },
    type: 'object',
    required: ['comment', 'log_id'],
    title: 'TutorFeedbackCreate'
} as const;

export const TutorFeedbackPublicSchema = {
    properties: {
        comment: {
            type: 'string',
            maxLength: 2000,
            title: 'Comment'
        },
        rating: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 5,
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rating'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        log_id: {
            type: 'string',
            format: 'uuid',
            title: 'Log Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['comment', 'id', 'log_id', 'owner_id', 'created_at'],
    title: 'TutorFeedbackPublic'
} as const;

export const TutorshipStatusSchema = {
    type: 'string',
    enum: ['pending', 'accepted', 'rejected'],
    title: 'TutorshipStatus'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        role: {
            '$ref': '#/components/schemas/UserRole',
            default: 'student_national'
        },
        specialty: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Specialty'
        },
        level: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Level'
        },
        language: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Language'
        },
        gpa: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Gpa'
        },
        can_access_dashboard: {
            type: 'boolean',
            title: 'Can Access Dashboard',
            default: false
        },
        can_apply_internship: {
            type: 'boolean',
            title: 'Can Apply Internship',
            default: false
        },
        can_view_convention: {
            type: 'boolean',
            title: 'Can View Convention',
            default: false
        },
        can_view_tracking: {
            type: 'boolean',
            title: 'Can View Tracking',
            default: false
        },
        can_review_applications: {
            type: 'boolean',
            title: 'Can Review Applications',
            default: false
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserDocumentPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        type: {
            '$ref': '#/components/schemas/DocumentType',
            default: 'other'
        },
        url: {
            type: 'string',
            maxLength: 512,
            title: 'Url'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['name', 'url', 'id', 'owner_id', 'created_at'],
    title: 'UserDocumentPublic'
} as const;

export const UserDocumentsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserDocumentPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UserDocumentsPublic'
} as const;

export const UserMinimalSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            type: 'string',
            title: 'Email'
        }
    },
    type: 'object',
    required: ['id', 'email'],
    title: 'UserMinimal'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        role: {
            '$ref': '#/components/schemas/UserRole',
            default: 'student_national'
        },
        specialty: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Specialty'
        },
        level: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Level'
        },
        language: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Language'
        },
        gpa: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Gpa'
        },
        can_access_dashboard: {
            type: 'boolean',
            title: 'Can Access Dashboard',
            default: false
        },
        can_apply_internship: {
            type: 'boolean',
            title: 'Can Apply Internship',
            default: false
        },
        can_view_convention: {
            type: 'boolean',
            title: 'Can View Convention',
            default: false
        },
        can_view_tracking: {
            type: 'boolean',
            title: 'Can View Tracking',
            default: false
        },
        can_review_applications: {
            type: 'boolean',
            title: 'Can Review Applications',
            default: false
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        role_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Role Type'
        },
        mobility_preference: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Mobility Preference'
        },
        interest_tags: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Interest Tags',
            default: []
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        role: {
            '$ref': '#/components/schemas/UserRole',
            default: 'student_national'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserRoleSchema = {
    type: 'string',
    enum: ['student_national', 'student_international', 'prof_national', 'prof_international', 'admin'],
    title: 'UserRole'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        role: {
            '$ref': '#/components/schemas/UserRole',
            default: 'student_national'
        },
        specialty: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Specialty'
        },
        level: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Level'
        },
        language: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Language'
        },
        gpa: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Gpa'
        },
        can_access_dashboard: {
            type: 'boolean',
            title: 'Can Access Dashboard',
            default: false
        },
        can_apply_internship: {
            type: 'boolean',
            title: 'Can Apply Internship',
            default: false
        },
        can_view_convention: {
            type: 'boolean',
            title: 'Can View Convention',
            default: false
        },
        can_view_tracking: {
            type: 'boolean',
            title: 'Can View Tracking',
            default: false
        },
        can_review_applications: {
            type: 'boolean',
            title: 'Can Review Applications',
            default: false
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const VerificationStatusSchema = {
    type: 'string',
    enum: ['idle', 'checking', 'verified', 'failed'],
    title: 'VerificationStatus'
} as const;