// This file is auto-generated by @hey-api/openapi-ts

export type ActivityLogEntriesPublic = {
    data: Array<ActivityLogEntryPublic>;
    count: number;
};

export type ActivityLogEntryCreate = {
    date: string;
    content: string;
    hours: number;
    internship_request_id: string;
};

export type ActivityLogEntryPublic = {
    date: string;
    content: string;
    hours: number;
    id: string;
    internship_request_id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type AlertItem = {
    id: string;
    type: string;
    severity: string;
    message: string;
    dossier_id: (string | null);
    created_at: unknown;
};

export type ApprovalLevel = 'N1' | 'N2' | 'N3';

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type ConventionCreate = {
    document_name: string;
    signature_step?: number;
    status?: string;
    approval_level?: ApprovalLevel;
    admin_status?: string;
    internship_request_id: string;
};

export type ConventionPublic = {
    document_name: string;
    signature_step?: number;
    status?: string;
    approval_level?: ApprovalLevel;
    admin_status?: string;
    id: string;
    internship_request_id: string;
    owner_id: string;
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type ConventionsPublic = {
    data: Array<ConventionPublic>;
    count: number;
};

export type ConventionUpdate = {
    document_name?: (string | null);
    signature_step?: (number | null);
    status?: (string | null);
    approval_level?: (ApprovalLevel | null);
    admin_status?: (string | null);
};

export type DashboardOverviewResponse = {
    internships: InternshipSummary;
    dossiers: DossierSummary;
    sla: SLASummary;
    signature: SignatureSummary;
    alerts: Array<AlertItem>;
    system_health: Array<SystemHealthItem>;
    timestamp: string;
};

export type DossierSummary = {
    total_dossiers: number;
    active_dossiers: number;
    completed_dossiers: number;
    pending_dossiers: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type InternshipOfferPublic = {
    title: string;
    description?: (string | null);
    source_url: string;
    published_date?: (string | null);
    target_audience?: (string | null);
    mobility_type?: (string | null);
    keywords?: Array<(string)>;
    translated_description?: (string | null);
    specialty?: (string | null);
    required_level?: (string | null);
    required_language?: (string | null);
    gpa_requirement?: (number | null);
    id: string;
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type InternshipOffersPublic = {
    data: Array<InternshipOfferPublic>;
    count: number;
};

export type InternshipReportCreate = {
    title: string;
    file_url?: (string | null);
    status?: ReportStatus;
    feedback?: (string | null);
    internship_request_id: string;
};

export type InternshipReportPublic = {
    title: string;
    file_url?: (string | null);
    status?: ReportStatus;
    feedback?: (string | null);
    id: string;
    internship_request_id: string;
    owner_id: string;
    submitted_at?: (string | null);
    reviewed_at?: (string | null);
};

export type InternshipReportsPublic = {
    data: Array<InternshipReportPublic>;
    count: number;
};

export type InternshipRequestCreate = {
    student_name: string;
    registration_number: string;
    email?: (string | null);
    birth_date?: (string | null);
    company_name?: (string | null);
    company_address?: (string | null);
    mission_title?: (string | null);
    mission_description?: (string | null);
    start_date?: (string | null);
    end_date?: (string | null);
    status?: InternshipStatus;
    verification_status?: VerificationStatus;
    progress?: number;
    current_step?: number;
};

export type InternshipRequestPublic = {
    student_name: string;
    registration_number: string;
    email?: (string | null);
    birth_date?: (string | null);
    company_name?: (string | null);
    company_address?: (string | null);
    mission_title?: (string | null);
    mission_description?: (string | null);
    start_date?: (string | null);
    end_date?: (string | null);
    status?: InternshipStatus;
    verification_status?: VerificationStatus;
    progress?: number;
    current_step?: number;
    id: string;
    owner_id: string;
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type InternshipRequestsPublic = {
    data: Array<InternshipRequestPublic>;
    count: number;
};

export type InternshipRequestUpdate = {
    student_name?: (string | null);
    registration_number?: (string | null);
    email?: (string | null);
    birth_date?: (string | null);
    company_name?: (string | null);
    company_address?: (string | null);
    mission_title?: (string | null);
    mission_description?: (string | null);
    start_date?: (string | null);
    end_date?: (string | null);
    status?: (InternshipStatus | null);
    verification_status?: (VerificationStatus | null);
    progress?: (number | null);
    current_step?: (number | null);
};

export type InternshipStatus = 'draft' | 'pending_verification' | 'pending_signature' | 'active' | 'completed' | 'blocked';

export type InternshipSummary = {
    total_internships: number;
    latest_internships: Array<{
        [key: string]: unknown;
    }>;
    new_items_7d: number;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type MobilityFileCreate = {
    reference_code: string;
    student_name: string;
    destination: string;
    mobility_type: MobilityType;
    approval_level?: ApprovalLevel;
    priority?: Priority;
    tags?: string;
    status?: string;
};

export type MobilityFilePublic = {
    reference_code: string;
    student_name: string;
    destination: string;
    mobility_type: MobilityType;
    approval_level?: ApprovalLevel;
    priority?: Priority;
    tags?: string;
    status?: string;
    id: string;
    owner_id: string;
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type MobilityFilesPublic = {
    data: Array<MobilityFilePublic>;
    count: number;
};

export type MobilityFileUpdate = {
    reference_code?: (string | null);
    student_name?: (string | null);
    destination?: (string | null);
    mobility_type?: (MobilityType | null);
    approval_level?: (ApprovalLevel | null);
    priority?: (Priority | null);
    tags?: (string | null);
    status?: (string | null);
};

export type MobilityType = 'nationale' | 'internationale';

export type NewPassword = {
    token: string;
    new_password: string;
};

export type Priority = 'Low' | 'Medium' | 'High' | 'Critical';

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type RecommendationResponse = {
    results: Array<RecommendationResultItem>;
    is_fallback: boolean;
    message: (string | null);
};

export type RecommendationResultItem = {
    offer: InternshipOfferPublic;
    score: number;
    breakdown?: ({
    [key: string]: (number);
} | null);
    warnings?: (Array<(string)> | null);
};

export type ReportStatus = 'pending' | 'reviewed' | 'approved' | 'rejected';

export type SignatureSummary = {
    average_progress: number;
    stalled_dossiers: number;
    completed_signatures: number;
};

export type SLASummary = {
    total_dossiers: number;
    on_time_count: number;
    breached_count: number;
    breach_rate: number;
};

export type StageRequestCreate = {
    selected_mobility_type: string;
    selected_interests?: Array<(string)>;
    duration_preference?: (string | null);
    specialty?: (string | null);
    level?: (string | null);
    language?: (string | null);
    gpa?: (number | null);
};

export type SystemHealthItem = {
    name: string;
    status: string;
    latency: string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type TutorEvaluationCreate = {
    rating: number;
    comment?: (string | null);
    internship_request_id: string;
};

export type TutorEvaluationPublic = {
    rating: number;
    comment?: (string | null);
    id: string;
    internship_request_id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    role?: UserRole;
    specialty?: (string | null);
    level?: (string | null);
    language?: (string | null);
    gpa?: (number | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    role?: UserRole;
    specialty?: (string | null);
    level?: (string | null);
    language?: (string | null);
    gpa?: (number | null);
    id: string;
    created_at?: (string | null);
    role_type?: (string | null);
    mobility_preference?: (string | null);
    interest_tags?: Array<(string)>;
    // DB-driven permission flags
    can_access_dashboard?: boolean;
    can_apply_internship?: boolean;
    can_view_convention?: boolean;
    can_view_tracking?: boolean;
    can_review_applications?: boolean;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
    role?: UserRole;
};

// Role is metadata only — access is controlled by DB permission boolean flags.
export type UserRole = 'student_national' | 'student_international' | 'prof_national' | 'prof_international' | 'admin';

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    role?: UserRole;
    specialty?: (string | null);
    level?: (string | null);
    language?: (string | null);
    gpa?: (number | null);
    password?: (string | null);
    // DB-driven permission flags
    can_access_dashboard?: (boolean | null);
    can_apply_internship?: (boolean | null);
    can_view_convention?: (boolean | null);
    can_view_tracking?: (boolean | null);
    can_review_applications?: (boolean | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type VerificationStatus = 'idle' | 'checking' | 'verified' | 'failed';

export type ActivityLogReadActivityLogData = {
    internshipRequestId: string;
    limit?: number;
    skip?: number;
};

export type ActivityLogReadActivityLogResponse = (ActivityLogEntriesPublic);

export type ActivityLogCreateLogEntryData = {
    requestBody: ActivityLogEntryCreate;
};

export type ActivityLogCreateLogEntryResponse = (ActivityLogEntryPublic);

export type ConventionsReadConventionsData = {
    limit?: number;
    skip?: number;
};

export type ConventionsReadConventionsResponse = (ConventionsPublic);

export type ConventionsCreateConventionEndpointData = {
    requestBody: ConventionCreate;
};

export type ConventionsCreateConventionEndpointResponse = (ConventionPublic);

export type ConventionsReadConventionData = {
    id: string;
};

export type ConventionsReadConventionResponse = (ConventionPublic);

export type ConventionsUpdateConventionEndpointData = {
    id: string;
    requestBody: ConventionUpdate;
};

export type ConventionsUpdateConventionEndpointResponse = (ConventionPublic);

export type ConventionsDeleteConventionEndpointData = {
    id: string;
};

export type ConventionsDeleteConventionEndpointResponse = (Message);

export type ConventionsSignConventionData = {
    id: string;
};

export type ConventionsSignConventionResponse = (ConventionPublic);

export type ConventionsReadAllConventionsAdminData = {
    limit?: number;
    skip?: number;
};

export type ConventionsReadAllConventionsAdminResponse = (ConventionsPublic);

export type ConventionsApproveConventionEndpointData = {
    id: string;
};

export type ConventionsApproveConventionEndpointResponse = (ConventionPublic);

export type ConventionsRejectConventionEndpointData = {
    id: string;
    reason?: string;
};

export type ConventionsRejectConventionEndpointResponse = (ConventionPublic);

export type ConventionsForwardConventionEndpointData = {
    id: string;
    nextLevel: ApprovalLevel;
};

export type ConventionsForwardConventionEndpointResponse = (ConventionPublic);

export type HealthHealthResponse = (unknown);

export type InternshipsReadInternshipRequestsData = {
    limit?: number;
    skip?: number;
};

export type InternshipsReadInternshipRequestsResponse = (InternshipRequestsPublic);

export type InternshipsCreateInternshipData = {
    requestBody: InternshipRequestCreate;
};

export type InternshipsCreateInternshipResponse = (InternshipRequestPublic);

export type InternshipsReadInternshipRequestData = {
    id: string;
};

export type InternshipsReadInternshipRequestResponse = (InternshipRequestPublic);

export type InternshipsUpdateInternshipData = {
    id: string;
    requestBody: InternshipRequestUpdate;
};

export type InternshipsUpdateInternshipResponse = (InternshipRequestPublic);

export type InternshipsDeleteInternshipData = {
    id: string;
};

export type InternshipsDeleteInternshipResponse = (Message);

export type InternshipsRefreshOffersResponse = ({
    [key: string]: unknown;
});

export type InternshipsReadOffersData = {
    limit?: number;
    skip?: number;
};

export type InternshipsReadOffersResponse = (InternshipOffersPublic);

export type InternshipsReadRecommendedOffersData = {
    limit?: number;
};

export type InternshipsReadRecommendedOffersResponse = (Array<{
    [key: string]: unknown;
}>);

export type InternshipsReadOfferData = {
    id: string;
};

export type InternshipsReadOfferResponse = (InternshipOfferPublic);

export type InternshipsLogInteractionData = {
    eventType: string;
    id: string;
};

export type InternshipsLogInteractionResponse = ({
    [key: string]: unknown;
});

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type MobilityReadMobilityFilesData = {
    limit?: number;
    mobilityType?: (MobilityType | null);
    skip?: number;
};

export type MobilityReadMobilityFilesResponse = (MobilityFilesPublic);

export type MobilityCreateMobilityData = {
    requestBody: MobilityFileCreate;
};

export type MobilityCreateMobilityResponse = (MobilityFilePublic);

export type MobilityReadMobilityFileData = {
    id: string;
};

export type MobilityReadMobilityFileResponse = (MobilityFilePublic);

export type MobilityUpdateMobilityData = {
    id: string;
    requestBody: MobilityFileUpdate;
};

export type MobilityUpdateMobilityResponse = (MobilityFilePublic);

export type MobilityDeleteMobilityData = {
    id: string;
};

export type MobilityDeleteMobilityResponse = (Message);

export type MobilityReadInternshipSummaryData = {
    id: string;
};

export type MobilityReadInternshipSummaryResponse = ({
    [key: string]: unknown;
});

export type MobilityReadReportsData = {
    internshipId: string;
    limit?: number;
    skip?: number;
};

export type MobilityReadReportsResponse = (InternshipReportsPublic);

export type MobilityCreateReportData = {
    requestBody: InternshipReportCreate;
};

export type MobilityCreateReportResponse = (InternshipReportPublic);

export type MobilityReadEvaluationData = {
    internshipId: string;
};

export type MobilityReadEvaluationResponse = ((TutorEvaluationPublic | null));

export type MobilityCreateEvaluationData = {
    requestBody: TutorEvaluationCreate;
};

export type MobilityCreateEvaluationResponse = (TutorEvaluationPublic);

export type OverviewGetOverviewDataResponse = (DashboardOverviewResponse);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type RecommendationsReadUserProfileResponse = (UserPublic);

export type RecommendationsSubmitStageRequestData = {
    debug?: boolean;
    requestBody: StageRequestCreate;
};

export type RecommendationsSubmitStageRequestResponse = (RecommendationResponse);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);