"""Add partnerships table

Revision ID: 1b89afeda774
Revises: 28899c1fdf86
Create Date: 2026-05-01 15:27:51.038410

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1b89afeda774'
down_revision = '28899c1fdf86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partnership',
    sa.Column('partner_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('partner_type', sa.Enum('university', 'company', name='partnertype'), nullable=False),
    sa.Column('contact_email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('contact_phone', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('active', 'expired', 'pending', name='partnershipstatus'), nullable=False),
    sa.Column('document_url', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('partnership')
    # ### end Alembic commands ###
