"""align_internship_offers_for_recommendation

Revision ID: 2286350b0c46
Revises: c1eb823b934a
Create Date: 2026-05-01 05:07:04.620401

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2286350b0c46'
down_revision = 'c1eb823b934a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert')
    op.drop_table('mobilityfile')
    op.drop_table('activitylogentry')
    op.drop_table('convention')
    op.drop_table('internshiprequest')
    op.add_column('internshipoffer', sa.Column('translated_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('internshipoffer', sa.Column('specialty', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('internshipoffer', sa.Column('required_level', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('internshipoffer', sa.Column('required_language', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('internshipoffer', sa.Column('gpa_requirement', sa.Float(), nullable=True))
    op.alter_column('stagerequest', 'processed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user', 'total_sessions',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'engagement_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('user', 'profile_locked',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'profile_locked',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user', 'engagement_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('user', 'total_sessions',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('stagerequest', 'processed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('internshipoffer', 'gpa_requirement')
    op.drop_column('internshipoffer', 'required_language')
    op.drop_column('internshipoffer', 'required_level')
    op.drop_column('internshipoffer', 'specialty')
    op.drop_column('internshipoffer', 'translated_description')
    op.create_table('internshiprequest',
    sa.Column('student_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('registration_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('birth_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('company_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('company_address', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('mission_title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('mission_description', sa.VARCHAR(length=2000), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('draft', 'pending_verification', 'pending_signature', 'active', 'completed', 'blocked', name='internshipstatus'), autoincrement=False, nullable=False),
    sa.Column('verification_status', postgresql.ENUM('idle', 'checking', 'verified', 'failed', name='verificationstatus'), autoincrement=False, nullable=False),
    sa.Column('progress', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('current_step', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_activity_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('internshiprequest_owner_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('internshiprequest_pkey'))
    )
    op.create_table('convention',
    sa.Column('document_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('signature_step', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('internship_request_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['internship_request_id'], ['internshiprequest.id'], name=op.f('convention_internship_request_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('convention_owner_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('convention_pkey'))
    )
    op.create_table('activitylogentry',
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(length=2000), autoincrement=False, nullable=False),
    sa.Column('hours', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('internship_request_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['internship_request_id'], ['internshiprequest.id'], name=op.f('activitylogentry_internship_request_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('activitylogentry_owner_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('activitylogentry_pkey'))
    )
    op.create_table('mobilityfile',
    sa.Column('reference_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('student_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('destination', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('mobility_type', postgresql.ENUM('nationale', 'internationale', name='mobilitytype'), autoincrement=False, nullable=False),
    sa.Column('approval_level', postgresql.ENUM('N1', 'N2', 'N3', name='approvallevel'), autoincrement=False, nullable=False),
    sa.Column('priority', postgresql.ENUM('Low', 'Medium', 'High', 'Critical', name='prioritylevel'), autoincrement=False, nullable=False),
    sa.Column('tags', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('mobilityfile_owner_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('mobilityfile_pkey'))
    )
    op.create_table('alert',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('severity', postgresql.ENUM('info', 'warning', 'critical', name='alertseverity'), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('dossier_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dossier_id'], ['internshiprequest.id'], name=op.f('alert_dossier_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('alert_pkey'))
    )
    # ### end Alembic commands ###
