"""rename_description_to_content_final

Revision ID: 28899c1fdf86
Revises: 6332305353e4
Create Date: 2026-05-01 10:10:09.209128

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '28899c1fdf86'
down_revision = '6332305353e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activitylog',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('attachment_url', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('internship_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['internship_id'], ['internshiprequest.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tutorfeedback',
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('log_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['log_id'], ['activitylog.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tutorfeedback')
    op.drop_table('activitylog')
    # ### end Alembic commands ###
