"""Add convention approval fields

Revision ID: 40259b3e41e7
Revises: 2286350b0c46
Create Date: 2026-05-01 08:17:24.148320

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '40259b3e41e7'
down_revision = '2286350b0c46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Use exist_ok=True or check if enum exists if necessary, but here we assume it might exist from mobilityfile
    op.add_column('convention', sa.Column('approval_level', sa.Enum('N1', 'N2', 'N3', name='approvallevel'), nullable=True))
    op.execute("UPDATE convention SET approval_level = 'N1'")
    op.alter_column('convention', 'approval_level', nullable=False)
    
    op.add_column('convention', sa.Column('admin_status', sa.String(length=50), nullable=True))
    op.execute("UPDATE convention SET admin_status = 'pending'")
    op.alter_column('convention', 'admin_status', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activitylogentry',
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(length=2000), autoincrement=False, nullable=False),
    sa.Column('hours', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('internship_request_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['internship_request_id'], ['internshiprequest.id'], name=op.f('activitylogentry_internship_request_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('activitylogentry_owner_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('activitylogentry_pkey'))
    )
    op.create_table('convention',
    sa.Column('document_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('signature_step', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('internship_request_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['internship_request_id'], ['internshiprequest.id'], name=op.f('convention_internship_request_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('convention_owner_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('convention_pkey'))
    )
    op.create_table('mobilityfile',
    sa.Column('reference_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('student_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('destination', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('mobility_type', postgresql.ENUM('nationale', 'internationale', name='mobilitytype'), autoincrement=False, nullable=False),
    sa.Column('approval_level', postgresql.ENUM('N1', 'N2', 'N3', name='approvallevel'), autoincrement=False, nullable=False),
    sa.Column('priority', postgresql.ENUM('low', 'medium', 'high', 'critical', name='priority'), autoincrement=False, nullable=False),
    sa.Column('tags', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('mobilityfile_owner_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('mobilityfile_pkey'))
    )
    op.create_table('internshiprequest',
    sa.Column('student_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('registration_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('birth_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('company_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('company_address', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('mission_title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('mission_description', sa.VARCHAR(length=2000), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('draft', 'pending_verification', 'pending_signature', 'active', 'completed', 'blocked', name='internshipstatus'), autoincrement=False, nullable=False),
    sa.Column('verification_status', postgresql.ENUM('idle', 'checking', 'verified', 'failed', name='verificationstatus'), autoincrement=False, nullable=False),
    sa.Column('progress', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('current_step', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_activity_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('internshiprequest_owner_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('internshiprequest_pkey'))
    )
    op.create_table('alert',
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('severity', postgresql.ENUM('info', 'warning', 'critical', name='alertseverity'), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('dossier_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dossier_id'], ['internshiprequest.id'], name=op.f('alert_dossier_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('alert_pkey'))
    )
    # ### end Alembic commands ###
