"""add mobility details

Revision ID: 41328221ca1a
Revises: 4a2f8d3bee40
Create Date: 2026-05-02 01:43:42.539649

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '41328221ca1a'
down_revision = '4a2f8d3bee40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mobilityfile', sa.Column('origin_university', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('mobilityfile', sa.Column('visa_status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('mobilityfile', sa.Column('file_transfer_status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mobilityfile', 'file_transfer_status')
    op.drop_column('mobilityfile', 'visa_status')
    op.drop_column('mobilityfile', 'origin_university')
    # ### end Alembic commands ###
