"""add_suivi_stage_models

Revision ID: 6332305353e4
Revises: 3082146b3404
Create Date: 2026-05-01 09:56:46.918120

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6332305353e4'
down_revision = '3082146b3404'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
