"""add_fields_to_stagerequest

Revision ID: c1eb823b934a
Revises: 01dd2aa87891
Create Date: 2026-05-01 04:51:50.198065

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c1eb823b934a'
down_revision = '01dd2aa87891'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stagerequest', sa.Column('specialty', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('stagerequest', sa.Column('level', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('stagerequest', sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('stagerequest', sa.Column('gpa', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stagerequest', 'gpa')
    op.drop_column('stagerequest', 'language')
    op.drop_column('stagerequest', 'level')
    op.drop_column('stagerequest', 'specialty')
    # ### end Alembic commands ###
