"""Add internship offers scraper table

Revision ID: eeacfe0ba015
Revises: c4dae50e75b1
Create Date: 2026-05-01 01:13:52.846931

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'eeacfe0ba015'
down_revision = 'c4dae50e75b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('internshipoffer',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=5000), nullable=True),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('published_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internshipoffer_source_url'), 'internshipoffer', ['source_url'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_internshipoffer_source_url'), table_name='internshipoffer')
    op.drop_table('internshipoffer')
    # ### end Alembic commands ###
