"""Add role column to User model

Revision ID: f1207e311c73
Revises: fe56fa70289e
Create Date: 2026-04-30 20:31:49.971812

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f1207e311c73'
down_revision = 'fe56fa70289e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    userrole = sa.Enum('student_national', 'student_international', 'prof_national', 'prof_international', 'admin', name='userrole')
    userrole.create(op.get_bind())
    op.add_column('user', sa.Column('role', userrole, nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    sa.Enum(name='userrole').drop(op.get_bind())
    # ### end Alembic commands ###
