"""Add role column to User model

Revision ID: f1207e311c73
Revises: fe56fa70289e
Create Date: 2026-04-30 20:31:49.971812

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f1207e311c73'
down_revision = 'fe56fa70289e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    result = bind.execute(sa.text("SELECT 1 FROM pg_type WHERE typname = 'userrole'"))
    if not result.scalar():
        userrole = sa.Enum('student_national', 'student_international', 'prof_national', 'prof_international', 'admin', name='userrole')
        userrole.create(bind)
    from sqlalchemy.dialects import postgresql
    op.add_column('user', sa.Column('role', postgresql.ENUM('student_national', 'student_international', 'prof_national', 'prof_international', 'admin', name='userrole', create_type=False), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    bind = op.get_bind()
    bind.execute(sa.text("DROP TYPE IF EXISTS userrole"))
    # ### end Alembic commands ###
