/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSuiviRouteImport } from './routes/_layout/suivi'
import { Route as LayoutStagesRouteImport } from './routes/_layout/stages'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutMobiliteRouteImport } from './routes/_layout/mobilite'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutConventionRouteImport } from './routes/_layout/convention'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSuiviRoute = LayoutSuiviRouteImport.update({
  id: '/suivi',
  path: '/suivi',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutStagesRoute = LayoutStagesRouteImport.update({
  id: '/stages',
  path: '/stages',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMobiliteRoute = LayoutMobiliteRouteImport.update({
  id: '/mobilite',
  path: '/mobilite',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutConventionRoute = LayoutConventionRouteImport.update({
  id: '/convention',
  path: '/convention',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/convention': typeof LayoutConventionRoute
  '/items': typeof LayoutItemsRoute
  '/mobilite': typeof LayoutMobiliteRoute
  '/settings': typeof LayoutSettingsRoute
  '/stages': typeof LayoutStagesRoute
  '/suivi': typeof LayoutSuiviRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/convention': typeof LayoutConventionRoute
  '/items': typeof LayoutItemsRoute
  '/mobilite': typeof LayoutMobiliteRoute
  '/settings': typeof LayoutSettingsRoute
  '/stages': typeof LayoutStagesRoute
  '/suivi': typeof LayoutSuiviRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/convention': typeof LayoutConventionRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/mobilite': typeof LayoutMobiliteRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/stages': typeof LayoutStagesRoute
  '/_layout/suivi': typeof LayoutSuiviRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/convention'
    | '/items'
    | '/mobilite'
    | '/settings'
    | '/stages'
    | '/suivi'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/convention'
    | '/items'
    | '/mobilite'
    | '/settings'
    | '/stages'
    | '/suivi'
    | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/convention'
    | '/_layout/items'
    | '/_layout/mobilite'
    | '/_layout/settings'
    | '/_layout/stages'
    | '/_layout/suivi'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/suivi': {
      id: '/_layout/suivi'
      path: '/suivi'
      fullPath: '/suivi'
      preLoaderRoute: typeof LayoutSuiviRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/stages': {
      id: '/_layout/stages'
      path: '/stages'
      fullPath: '/stages'
      preLoaderRoute: typeof LayoutStagesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/mobilite': {
      id: '/_layout/mobilite'
      path: '/mobilite'
      fullPath: '/mobilite'
      preLoaderRoute: typeof LayoutMobiliteRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/convention': {
      id: '/_layout/convention'
      path: '/convention'
      fullPath: '/convention'
      preLoaderRoute: typeof LayoutConventionRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutConventionRoute: typeof LayoutConventionRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutMobiliteRoute: typeof LayoutMobiliteRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutStagesRoute: typeof LayoutStagesRoute
  LayoutSuiviRoute: typeof LayoutSuiviRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutConventionRoute: LayoutConventionRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutMobiliteRoute: LayoutMobiliteRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutStagesRoute: LayoutStagesRoute,
  LayoutSuiviRoute: LayoutSuiviRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
